data:
  dataset_name_or_path: /home/mingyang/projs/OmniGen/data/pexels.txt
  spatial_size: 256
  num_frames: 17
  frame_intervals:
    - 1
    - 2
    - 4
    - 8

model:
  down_block_types:
    - SpatialDownBlock3D
    - SpatialTemporalDownBlock3D
    - SpatialTemporalDownBlock3D
  up_block_types:
    - TemporalUpBlock3D
    - TemporalUpBlock3D
    - SpatialUpBlock3D
    - SpatialUpBlock3D
    - SpatialUpBlock3D
  block_out_channels:
    - 128
    - 256
    - 256
    - 512
    - 512
  layers_per_block: 4

optimizer:
  learning_rate: 0.00025

runner:
  runner_cls_path: omni_gen.runners.vae_trainer.VAETrainer
  name: VideoVAE
  num_devices: 4
  train_batch_size: 2
  seed: 233
  use_ema: False
  gradient_accumulation_steps: 8
  zero_stage: 2
  gradient_checkpointing: False
  mixed_precision: bf16
  checkpointing_every_n_steps: 100
  kl_loss_weight: 0.0001
  discriminator_start_steps: 10000
  log_with: wandb
